### ISSUE TITLE
The indicators next to the UA are selectable allowing them to be copied out

### ISSUE THREAD

**Issue by Dreamy-Jazz** [GeneralNotability/InvestorGoat#2]
The indicators next to the UA in the 'Get edits' results are selectable and copyable which means that if copying the text of the get edits results to be pasted to the checkuser wiki (such as log events that would be useful to keep for future reference) the indicators are copied also in the format 'DEVOSBR'. Making them not selectable should address this issue and can be done via CSS through 'user-select:none' and the prefixed versions for IE 11 and safari.

**Comment by GeneralNotability** [comment]
Done.
